name: 'Setup FMT'
description: 'Build and install the FMT C++ library'
author: 'maximeverreault'
inputs:
  version:
    required: false
    description: 'FMT version to build, e.g. `9.1.0`'
    default: 'latest'
  toolset:
    required: false
    description: 'The CMake generator used to generate the build system, e.g. `auto`, `Ninja`, `MinGW Makefiles`, `Visual Studio 17 2022`'
    default: 'auto'
  directory:
    required: false
    description: 'Build directory. Default is runner.temp/fmt'
    default: 'runner.temp/fmt'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
branding:
  icon: package
  color: blue
