name: 'Setup FMT'
description: 'Build and install the FMT C++ library'
author: 'maximeverreault'
inputs:
  version:
    required: false
    description: 'FMT version to build, e.g. `9.1.0`'
    default: 'latest'
  toolset:
    required: false
    description: 'auto, mingw, msvc, clang, gcc'
    default: 'auto'
  platform:
    required: false
    description: 'x64 or x86'
    default: 'x64'
  directory:
    required: false
    description: 'Build directory. Default is runner.temp/fmt'
    default: 'runner.temp/fmt'
runs:
  using: 'node16'
  main: 'dist/index.js'
